/* -- CREATE DATABASE manomano;
-- USE manomano;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS lists;
DROP TABLE IF EXISTS lists_products;

-- MySQL Script generated by MySQL Workbench
-- Wed Jan 19 22:25:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema manomano
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema manomano
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `manomano` DEFAULT CHARACTER SET utf8 ;
USE `manomano` ;

-- -----------------------------------------------------
-- Table `manomano`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manomano`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manomano`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manomano`.`products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `picture` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `review` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;

INSERT INTO `products` (`id_product`, `title`, `picture`, `price`, `review`) VALUES 
(1, "stroller", "strollerImg.jpg", 158, "photo review1"),
(2, "shelf", "shelfImg.jpg", 45, "photo review1"),
(3, "drill", "drillImg.jpg", 109, "photo review1"),
(4, "radiator", "radiatorImg.jpg", 222, "photo review1"),
(5, "chainsaw", "chainsawImg.jpg", 359, "photo review1"),
(6, "drawer", "drawerImg.jpg", 99, "photo review1"),
(7, "lamp", "lampImg.jpg", 59, "photo review1"),
(8, "tv", "tvImg.jpg", 195, "photo review1"),
(9, "queenBed", "queenBedImg.jpg", 499, "photo review1"),
(10, "singleBed", "singleBedImg.jpg", 329, "photo review1");


-- -----------------------------------------------------
-- Table `manomano`.`lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manomano`.`lists` (
  `id_list` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_list`, `id_user`),
  INDEX `fk_List_users_id` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_List_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `manomano`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `lists` (`id_user`, `name`) VALUES 
(1, "Bathroom"),
(1, "Kitchen");


-- -----------------------------------------------------
-- Table `manomano`.`products_has_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manomano`.`lists_products` (
  `id_product` INT NOT NULL,
  `id_list` INT NOT NULL,
  PRIMARY KEY (`id_product`, `id_list`),
  INDEX `fk_lists_products_lists1_idx` (`id_list` ASC) VISIBLE,
  INDEX `fk_lists_products_products1_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `fk_lists_products_products1`
    FOREIGN KEY (`id_product`)
    REFERENCES `manomano`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lists_products_lists1`
    FOREIGN KEY (`id_list`)
    REFERENCES `manomano`.`lists` (`id_list`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `lists_products` (`id_product`, `id_list`) VALUES 
(1, 1),
(2, 1),
(3, 1),
(1, 2),
(4, 2),
(5, 2);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */

CREATE DATABASE wild_hackathon_mano_mano;
USE wild_hackathon_mano_mano;

DROP TABLE IF EXISTS lists_products;
DROP TABLE IF EXISTS users_products;
DROP TABLE IF EXISTS lists;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS products;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;

INSERT INTO `users` (`id_user`, `email`, `password`) VALUES 
(1, "Toto", "Toto");


-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `picture` VARCHAR(255) NOT NULL,
  `price` float NOT NULL,
  `review` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;

INSERT INTO `products` (`id_product`, `title`, `picture`, `price`, `review`) VALUES 
(1, "PawHut Pet Travel Stroller Cat Dog Pushchair Trolley Puppy Jogger Carrier Three Wheels", "strollerImg.jpg", 174, "photo review1"),
(2, "Ladder Shelf Industrial Pipe Wall Shelf Display Rack Plant Stand Bookcase", "shelfImg.jpg", 40, "photo review1"),
(3, "HP457DWE10 18v Combi Drill Li-ion with 2 Batteries", "drillImg.jpg", 250, "photo review1"),
(4, "Hudson Reed Delta – Radiateur Design Électrique Horizontal  – 63.5 x 84 x 4.6cm 800 Watts", "radiatorImg.jpg", 400, "photo review1"),
(5, "Aluminum Electric Chainsaw Garden Tools Double Brake Cover Case Blade Corded 40 cm", "chainsawImg.jpg", 600, "photo review1"),
(6, "Atlantic Bed Frame in White, size Small Double", "queenBedImg.jpg", 84, "photo review1"),
(7, "Drawer Chest of Drawers Bedroom Storage Furniture", "drawerImg.jpg", 89, "photo review1"),
(8, "Floor Lamp Modern Standing 3-in-1 Shelf LED Lamp with Storage Black", "lampImg.jpg", 45, "photo review1"),
(9, "Woodford Wooden Bed Frame Grey & Pine - Single", "singleBedImg.jpg", 79, "photo review1"),
(10, "Mobile TV Stand on Wheels Rolling", "tvImg.jpg", 55, "photo review1");


-- -----------------------------------------------------
-- Table `lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lists` (
  `id_list` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_list`),
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_user`))
ENGINE = InnoDB;


INSERT INTO `lists` (`id_list`, `id_user`, `name`) VALUES 
(1, 1, "House"),
(2, 1, "Tools");


-- -----------------------------------------------------
-- Table `lists_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lists_products` (
  `id_list` INT NOT NULL,
  `id_product` INT NOT NULL,
    FOREIGN KEY (`id_list`)
    REFERENCES `lists` (`id_list`),
    FOREIGN KEY (`id_product`)
    REFERENCES `products` (`id_product`))
ENGINE = InnoDB;


INSERT INTO `lists_products` (`id_list`, `id_product`) VALUES 
(1, 2),
(1, 7),
(2, 3);

-- -----------------------------------------------------
-- Table `users_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_products` (
  `id_user` INT NOT NULL,
  `id_product` INT NOT NULL,
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_user`),
    FOREIGN KEY (`id_product`)
    REFERENCES `products` (`id_product`))
ENGINE = InnoDB;


INSERT INTO `users_products` (`id_user`, `id_product`) VALUES 
(1, 1),
(1, 3),
(1, 5);